### PR TITLE
Update to use MIT license instead of MS-PL

### PR DESCRIPTION
**Pull request by ElijahReva**
PR for https://github.com/RolandPheasant/DynamicData/issues/117

### CODE REVIEW

**Comment by glennawatson** [comment]
DynamicData/DynamicData.csproj would also need updating.

**Comment by ElijahReva** [comment]
I've updated it together with `DynamicData.ReactiveUI` project

**Comment by ElijahReva** [comment]
Fixed

**Comment by RolandPheasant** [comment]
I'll notice the community on Slack and assuming there are no objections, I will accepts this change

**Comment by robsonj** [comment]
I basically defer to Roland, if its ok with Roland, its ok with me.
I hereby release all of my contributions to this project under the terms of the MIT license.

**Comment by ghuntley** [comment]
Yup ship it. MIT!

**Comment by modplug** [comment]
I'm OK with this 👍

**Comment by PureWeen** [comment]
MIT 👍👍👍👍👍👍👍

**Pull request merged**
