### PR TITLE
#132 - Allow connecting to any IEnumerable<T>

### PR DESCRIPTION
**Pull request by robsonj**
Added IEnumerable<TObject> extension methods to convert to a 

IObservable<IChangeSet<TObject, TKey>>

and a
 
IObservable<IChangeSet<TObject>>

### CODE REVIEW

**Comment by robsonj** [comment]
Yep. I’ll adjust

**Comment by robsonj** [comment]
No dice on moving them. Still fails tests. Renaming to AsObservableChangeSet() solves the issue however, if that’s a reasonable name?

**Comment by RolandPheasant** [comment]
Change it to that for now. I will merge it and have a play about to see fix the overload resolution issue.

**Comment by robsonj** [comment]
Ok, I 'think' you should have the additional changes. Never quite clear to me what magic the GitHub website is doing :-)

**Pull request merged**
